#!/bin/bash
echo "---installing python figlet toilet"
apt install python figlet toilet -y
echo "---installing modules"
pip install requests
echo "---installing smsbomber"
curl -LO https://raw.githubusercontent.com/Anon4You/smsbomber/main/smsbomber
mv smsbomber $PREFIX/bin
chmod +x $PREFIX/bin/smsbomber
figlet installed
echo "now you can run the tool by typing"$'\e[32m'" smsbomber "$'\e[0m'
